### PR TITLE
feat(hatch): added support and fixed some errors

### LINKED ISSUE #44: invalid value nil at index 1 in table for concat
image

PyLsp doens't detect my poetry environment so I am trying to understand what is happening.
Maybe because in this venv there isn't pylsp? There is on the system so it should find something.

### PR DESCRIPTION
**Pull request by Mte90**
Fix https://github.com/HallerPatrick/py_lsp.nvim/issues/44

I also implemented some error checking for some edge cases that I had.

### CODE REVIEW

**Comment by HallerPatrick** [comment]
Thank you very much @Mte90 !

File: lua/py_lsp/python/strategies.lua [hunk 1]
```diff
@@ -58,16 +64,26 @@ M.conda = function(_, venv_name)
...
 
 		table.insert(found_envs, path.join(env, "bin", "python"))
 	end
 
 	return found_envs
 end
 
+M.hatch = function(_, venv_name)
+	local venv = vim.fn.trim(vim.fn.system("hatch env find"))
+	print(venv)
```
Comment (Mte90) [inline lua/py_lsp/python/strategies.lua:79]: I noticed that I left this print @HallerPatrick...

Comment (Mte90) [reply lua/py_lsp/python/strategies.lua:79]: can you do a commit to remove this print or you need a new PR @HallerPatrick

Comment (HallerPatrick) [reply lua/py_lsp/python/strategies.lua:79]: Removed it :)
